### ISSUE TITLE
Learn how to write business requirements for software

### ISSUE THREAD

**Issue by shahwan42** [shahwan42/drug-interaction-checker#4]
close this issue when you finish and write the resources you learned from in the comments

**Comment by B0YK4** [comment]
[Programming Methodologies tutorialspoint](https://www.tutorialspoint.com/programming_methodologies/index.htm):
* Introduction
* Understanding the Problem
* Identifying the Solution

[Software Requirements Specification document with example](https://krazytech.com/projects/sample-software-requirements-specificationsrs-report-airline-database)
